"""Explainer figures for the catchment graph algorithm (docs/figures/alg-*.png).

The professor's ask: graphs that make the algorithm understandable. Every panel
is generated by the *real* engine code (``build_flow_model``, ``stream_mask``,
``rank_sites``) on a small synthetic Y-valley, so the pictures cannot drift
from the implementation. Muted single-hue colour maps, no chartjunk.

Run: uv run python scripts/make_algorithm_figures.py
"""

from __future__ import annotations

from collections import deque
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrow, FancyBboxPatch

from app.domain.geo import GridSpec
from app.domain.raster import Raster
from app.engines.hydrology.conditioning import fill_depressions
from app.engines.hydrology.flow import build_flow_model, stream_mask
from app.engines.hydrology.siting import rank_sites
from app.engines.terrain.derived import topographic_wetness_index
from app.engines.terrain.surfaces import slope_degrees

OUT = Path(__file__).resolve().parents[1] / "docs" / "figures"
CELL = 10.0
ROWS, COLS = 24, 36
GRID = GridSpec(32644, 500_000.0, 2_350_000.0, CELL, ROWS, COLS)

INK = "#1a1a1a"
ACCENT = "#2f6f8f"  # muted steel blue — the report's accent
MUTED = "#8fa8b8"


def y_valley() -> Raster:
    """Two tributary valleys converging into one trunk that drains south."""
    cc, rr = np.meshgrid(np.arange(COLS), np.arange(ROWS))
    t = np.clip(rr / (ROWS * 0.55), 0, 1)
    axis_left = 10 + (COLS // 2 - 10) * t
    axis_right = (COLS - 10) - (COLS - 10 - COLS // 2) * t
    across = np.minimum(np.abs(cc - axis_left), np.abs(cc - axis_right))
    z = 100.0 + 0.12 * across * CELL + 0.02 * (ROWS - rr) * CELL
    return Raster(GRID, z)


def bfs_depths(model, outlet: tuple[int, int]) -> np.ndarray:
    """Breadth-first-search depth of every catchment cell from the outlet.

    The same traversal ``upstream_mask`` runs, kept here with the depth
    recorded so the wavefront can be drawn.
    """
    donors: dict[int, list[int]] = {}
    receiver = model.receiver.ravel()
    for idx, rec in enumerate(receiver):
        if rec >= 0:
            donors.setdefault(int(rec), []).append(idx)
    depth = np.full(ROWS * COLS, -1, dtype=int)
    start = outlet[0] * COLS + outlet[1]
    depth[start] = 0
    queue = deque([start])
    while queue:
        node = queue.popleft()
        for donor in donors.get(node, []):
            if depth[donor] < 0:
                depth[donor] = depth[node] + 1
                queue.append(donor)
    return depth.reshape(ROWS, COLS)


def fig_pipeline() -> None:
    """The analyzeContour pipeline as one left-to-right flow."""
    stages = [
        ("KML / KMZ\nupload", "parse: lxml,\nelevation strategy"),
        ("Contour\nvertices", "Delaunay TIN,\nlinear interp"),
        ("DEM grid\n(derived res.)", "Priority-Flood\n+ ε fill"),
        ("Flow graph\n(D8)", "steepest descent,\n1 out-edge/cell"),
        ("Accumulation\n+ streams", "topological sweep,\n≥ 5 ha channels"),
        ("Site ranking\n(MCDA)", "plateau, slope, TWI,\nimpoundment, NMS"),
        ("Catchment\n(reverse BFS)", "snap to channel,\nupstream walk"),
        ("JSON +\nwarnings", "units, uncertainty,\nedge cases named"),
    ]
    fig, ax = plt.subplots(figsize=(13.2, 2.4), dpi=170)
    ax.set_xlim(0, len(stages) * 1.64)
    ax.set_ylim(0, 2.1)
    ax.axis("off")
    for i, (title, sub) in enumerate(stages):
        x = i * 1.64 + 0.06
        box = FancyBboxPatch(
            (x, 0.55),
            1.4,
            1.15,
            boxstyle="round,pad=0.06",
            linewidth=1.2,
            edgecolor=ACCENT,
            facecolor="#eef3f6" if i not in (3, 6) else "#d8e6ee",
        )
        ax.add_patch(box)
        ax.text(
            x + 0.7, 1.38, title, ha="center", va="center", fontsize=8.6, color=INK, weight="bold"
        )
        ax.text(x + 0.7, 0.86, sub, ha="center", va="center", fontsize=7.0, color="#444")
        if i < len(stages) - 1:
            ax.add_patch(
                FancyArrow(
                    x + 1.48,
                    1.12,
                    0.13,
                    0,
                    width=0.012,
                    head_width=0.09,
                    head_length=0.06,
                    color=MUTED,
                )
            )
    ax.text(
        0.06,
        0.18,
        "Highlighted stages are the graph algorithm: "
        "the D8 flow graph and the reverse breadth-first search over it.",
        fontsize=7.6,
        color="#444",
    )
    fig.savefig(OUT / "alg-pipeline.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)


def main() -> None:
    """Generate the four explainer figures."""
    OUT.mkdir(parents=True, exist_ok=True)
    fig_pipeline()

    dem = y_valley()
    fill = fill_depressions(dem)
    model = build_flow_model(fill.filled)
    streams = stream_mask(model, 40 * GRID.cell_area)
    acc = model.accumulation.astype(float)

    # ---- figure: DEM -> D8 flow graph -> accumulation ------------------
    fig, axes = plt.subplots(1, 3, figsize=(13.2, 3.6), dpi=170)
    ax = axes[0]
    im = ax.imshow(dem.data, cmap="Greys_r")
    cs = ax.contour(dem.data, levels=10, colors=ACCENT, linewidths=0.7)
    ax.clabel(cs, fontsize=5, fmt="%.0f")
    ax.set_title("a — terrain: contours on the DEM grid", fontsize=8.5)
    plt.colorbar(im, ax=ax, shrink=0.8, label="elevation (m)")

    ax = axes[1]
    ax.imshow(fill.filled.data, cmap="Greys_r", alpha=0.55)
    receiver = model.receiver
    for r in range(ROWS):
        for c in range(COLS):
            rec = int(receiver[r, c])
            if rec < 0:
                continue
            drow, dcol = rec // COLS - r, rec % COLS - c
            ax.arrow(
                c,
                r,
                dcol * 0.62,
                drow * 0.62,
                head_width=0.16,
                head_length=0.14,
                fc=ACCENT,
                ec=ACCENT,
                linewidth=0.4,
                alpha=0.85,
                length_includes_head=True,
            )
    ax.set_title("b — D8 flow graph: every cell keeps one out-edge", fontsize=8.5)
    ax.set_xlim(-0.5, COLS - 0.5)
    ax.set_ylim(ROWS - 0.5, -0.5)

    ax = axes[2]
    im = ax.imshow(np.log10(acc), cmap="Blues")
    sr, sc = np.nonzero(streams)
    ax.scatter(sc, sr, s=4, color="#0b3d5c", label="stream (≥ threshold)")
    ax.set_title(
        "c — accumulation: descendants counted in one\n"
        "topological sweep; channels above the threshold",
        fontsize=8.5,
    )
    ax.legend(loc="lower left", fontsize=6.5, framealpha=0.9)
    plt.colorbar(im, ax=ax, shrink=0.8, label="log₁₀ cells upstream")
    for ax in axes:
        ax.set_xticks([])
        ax.set_yticks([])
    fig.tight_layout()
    fig.savefig(OUT / "alg-d8-graph.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)

    # ---- figure: catchment as reverse BFS ------------------------------
    outlet_row = int(ROWS * 0.8)
    outlet = (outlet_row, COLS // 2)
    depth = bfs_depths(model, outlet)
    fig, ax = plt.subplots(figsize=(6.6, 4.2), dpi=170)
    shown = np.where(depth >= 0, depth, np.nan)
    im = ax.imshow(shown, cmap="viridis")
    ax.imshow(np.where(depth < 0, 0.0, np.nan), cmap="Greys", vmin=-1, vmax=3, alpha=0.25)
    ax.scatter(
        [outlet[1]],
        [outlet[0]],
        marker="*",
        s=160,
        color="#c0392b",
        zorder=5,
        label="outlet (pour point)",
    )
    ax.scatter(sc, sr, s=3, color="white", alpha=0.6, label="stream cells")
    ax.set_title(
        "Catchment = reverse breadth-first search from the outlet.\n"
        "Colour is BFS depth — the order the wavefront reaches each cell.",
        fontsize=8.8,
    )
    ax.legend(loc="lower left", fontsize=6.8, framealpha=0.9)
    plt.colorbar(im, ax=ax, shrink=0.85, label="BFS depth (cells from outlet)")
    ax.set_xticks([])
    ax.set_yticks([])
    fig.tight_layout()
    fig.savefig(OUT / "alg-catchment-bfs.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)

    # ---- figure: the existing-river edge case --------------------------
    slope = slope_degrees(dem).data
    twi = topographic_wetness_index(dem, model.accumulation).data
    bounds = (0.05, 0.2, 1.0, 2.5)  # hectares, scaled to this toy grid
    result = rank_sites(
        model, slope, twi, streams, top_n=3, suppression_radius_m=60.0, area_bounds_ha=bounds
    )
    area_ha = model.upstream_area_m2() / 1e4
    river = streams & (area_ha >= bounds[3])
    fig, ax = plt.subplots(figsize=(6.6, 4.2), dpi=170)
    ax.imshow(fill.filled.data, cmap="Greys_r", alpha=0.5)
    ax.scatter(sc, sr, s=10, c=area_ha[sr, sc], cmap="Blues", label="drainage network")
    rr_river, cc_river = np.nonzero(river)
    ax.scatter(
        cc_river,
        rr_river,
        s=34,
        marker="x",
        color="#c0392b",
        linewidths=1.2,
        label=f"river: ≥ {bounds[3]:g} ha upstream — excluded outright",
    )
    for i, cand in enumerate(result.candidates):
        ax.scatter(
            [cand.col],
            [cand.row],
            s=120,
            facecolors="none",
            edgecolors="#1e8449",
            linewidths=1.8,
            zorder=5,
        )
        ax.annotate(
            f"#{i + 1}",
            (cand.col + 0.8, cand.row - 0.8),
            fontsize=8,
            color="#1e8449",
            weight="bold",
        )
    ax.set_title(
        "Edge case: an existing watercourse. Channel cells beyond the plateau's upper\n"
        "bound are a river — hard-excluded; candidates land on tributaries and are reported.",
        fontsize=8.6,
    )
    ax.legend(loc="lower left", fontsize=6.8, framealpha=0.9)
    ax.set_xticks([])
    ax.set_yticks([])
    fig.tight_layout()
    fig.savefig(OUT / "alg-river-exclusion.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)

    print("wrote", *(sorted(p.name for p in OUT.glob("alg-*.png"))))


if __name__ == "__main__":
    main()
