"""Evidence figures for the report (docs/figures/), regenerated by `make figures`.

Runs the engine directly on the provided sample — no server needed — and
writes: sink-fill before/after, flow accumulation, and the pour-point
sensitivity plot (evidence register rows 6, 7 and 13).
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.engines.hydrology.catchment import delineate, snap_to_drainage  # noqa: E402
from app.engines.hydrology.conditioning import fill_depressions  # noqa: E402
from app.engines.hydrology.flow import build_flow_model, stream_mask  # noqa: E402
from app.engines.terrain.interpolate import contours_to_dem  # noqa: E402
from app.providers.contour_kml import parse_contours  # noqa: E402

SAMPLE = ROOT / "data" / "samples" / "contours_1m.kml"
OUT = ROOT / "docs" / "figures"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    contours = parse_contours(SAMPLE.read_bytes(), SAMPLE.name)
    dem = contours_to_dem(contours, floor_m=30.0).raster
    conditioned = fill_depressions(dem)
    model = build_flow_model(conditioned.filled)
    extent = dem.grid.bounds
    ext = (extent[0], extent[2], extent[1], extent[3])

    # 6. Sink fill before/after + difference
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.6))
    im = axes[0].imshow(dem.data, cmap="terrain", extent=ext)
    axes[0].set_title("Interpolated DEM (before)")
    fig.colorbar(im, ax=axes[0], label="m")
    im = axes[1].imshow(conditioned.filled.data, cmap="terrain", extent=ext)
    axes[1].set_title("Priority-Flood + ε (after)")
    fig.colorbar(im, ax=axes[1], label="m")
    im = axes[2].imshow(
        np.ma.masked_less_equal(conditioned.fill_depth.data, 1e-3), cmap="magma", extent=ext
    )
    axes[2].set_title(
        f"Fill depth — {conditioned.cells_filled} cells, max {conditioned.max_fill_m:.2f} m"
    )
    fig.colorbar(im, ax=axes[2], label="m")
    for ax in axes:
        ax.set_xlabel(f"EPSG:{dem.grid.epsg} easting (m)")
    fig.tight_layout()
    fig.savefig(OUT / "p2-sink-fill-before-after.png", dpi=130)

    # 7. Flow accumulation + streams
    fig, ax = plt.subplots(figsize=(7.5, 5.6))
    im = ax.imshow(np.log10(model.accumulation), cmap="magma", extent=ext)
    streams = stream_mask(model, 50_000.0)
    ax.contour(np.flipud(streams), levels=[0.5], colors="cyan", linewidths=0.6, extent=ext)
    ax.set_title("D8 flow accumulation (log10 cells) · streams ≥ 5 ha in cyan")
    fig.colorbar(im, ax=ax, label="log10 cells")
    fig.tight_layout()
    fig.savefig(OUT / "p2-flow-accumulation.png", dpi=130)

    # 13. Pour-point sensitivity: move ±3 cells around the largest interior channel cell.
    interior = model.accumulation.copy()
    interior[:3, :] = interior[-3:, :] = interior[:, :3] = interior[:, -3:] = 0
    flat = int(np.argmax(interior))
    r0, c0 = divmod(flat, model.shape[1])
    # choose a mid-sized channel instead of the outlet: the cell with ~25 % of max
    target = 0.25 * interior.max()
    flat = int(np.argmin(np.abs(interior - target)))
    r0, c0 = divmod(flat, model.shape[1])
    offsets = range(-3, 4)
    raw = np.full((7, 7), np.nan)
    snapped = np.full((7, 7), np.nan)
    for i, dr in enumerate(offsets):
        for j, dc in enumerate(offsets):
            r, c = r0 + dr, c0 + dc
            raw[i, j] = delineate(model, r, c, radius_m=1.0, min_area_m2=1.0).area_m2 / 1e4
            snapped[i, j] = delineate(model, r, c, radius_m=150.0, min_area_m2=20_000.0).area_m2 / 1e4
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.6))
    for ax, data, title in (
        (axes[0], raw, "No snapping — area at the clicked cell"),
        (axes[1], snapped, "Snap to nearest channel (≥ 2 ha, ≤ 150 m)"),
    ):
        im = ax.imshow(data, cmap="viridis", extent=(-3.5, 3.5, 3.5, -3.5))
        ax.set_title(title)
        ax.set_xlabel("column offset (cells)")
        ax.set_ylabel("row offset (cells)")
        for i in range(7):
            for j in range(7):
                ax.text(j - 3, i - 3, f"{data[i, j]:.0f}", ha="center", va="center", fontsize=7, color="w")
        fig.colorbar(im, ax=ax, label="catchment area (ha)")
    fig.suptitle(
        f"Pour-point sensitivity around cell ({r0}, {c0}): raw CV {np.nanstd(raw) / np.nanmean(raw):.0%}, "
        f"snapped CV {np.nanstd(snapped) / np.nanmean(snapped):.0%}"
    )
    fig.tight_layout()
    fig.savefig(OUT / "p2-pour-point-sensitivity.png", dpi=130)
    snap = snap_to_drainage(model, r0 + 2, c0 + 2, radius_m=150.0, min_area_m2=20_000.0)
    print(
        f"sensitivity centre ({r0},{c0}); raw CV {np.nanstd(raw) / np.nanmean(raw):.1%}; "
        f"snapped CV {np.nanstd(snapped) / np.nanmean(snapped):.1%}; example snap {snap.distance_m:.0f} m"
    )
    print("wrote", sorted(p.name for p in OUT.glob("p2-*.png")))


if __name__ == "__main__":
    main()
