"""Alembic environment.

The database URL is taken from ``app.core.config.Settings`` rather than from
``alembic.ini``, so migrations and the application can never disagree about
which database they are pointed at, and no credential is written to a file that
is committed.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings
from app.repositories.models import Base

config = context.config
config.set_main_option("sqlalchemy.url", get_settings().database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# The postgis image installs postgis, postgis_topology and the tiger geocoder,
# and puts `tiger` on the database search_path. Those tables are owned by the
# extensions, not by us. Without this filter every autogenerated revision opens
# with forty `op.drop_table` calls against them.
#
# The rule is deliberately the strict one: a *reflected* table that this
# metadata does not declare is not ours, so we neither create nor drop it.


def include_object(obj, name, type_, reflected, compare_to):  # type: ignore[no-untyped-def]
    """Restrict autogenerate to the tables this project declares."""
    return not (type_ == "table" and reflected and name not in target_metadata.tables)


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting — used to review a migration."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect and run migrations in a transaction."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
